### PR TITLE
Fix lazy loading of micromamba/pixi_jll

### LINKED ISSUE #170: SciMLBasePythonCallExt always precompiling, CondaPkg 0.2.25 regression
On Windows, `julia +lts --startup-file=no --project=debug` , `pkg> add PythonCall SciMLBase CondaPkg#compare-load-path`.

With Julia 1.10.8, versions are
```
  [992eb4ea] CondaPkg v0.2.25 `https://github.com/JuliaPy/CondaPkg.jl.git#compare-load-path`
  [6099a3de] PythonCall v0.9.24
  [0bca4576] SciMLBase v2.75.1
```

Then every time I start Julia, SciMLBasePythonCallExt gets precompiled.
```
julia> using PythonCall

julia> @time using SciMLBase
Precompiling SciMLBasePythonCallExt finished.
  1 dependency successfully precompiled in 3 seconds. 68 already precompiled.
[ Info: Precompiling SciMLBasePythonCallExt [2797fd30-2078-5027-980c-4c2c8a19c528]
  5.792371 seconds (4.77 M allocations: 370.907 MiB, 3.59% gc time, 25.51% compilation time)
```
This does not happen on CondaPkg 0.2.24.

I used `https://github.com/JuliaPy/CondaPkg.jl.git#compare-load-path` because that fixed #166 for me.

### PR DESCRIPTION
**Pull request by cjdoris**
Fixes #170. Fixes JuliaPy/PythonCall.jl#594.

### CODE REVIEW

File: test/internals.jl [hunk 1]
```diff
@@ -183,7 +183,7 @@ end
     packages =
         Dict("foo" => Dict("test.toml" => CondaPkg.PkgSpec("foo", channel = "bad-channel")))
     channels = [CondaPkg.ChannelSpec("conda-forge")]
-    @test nothing ===
+    @test true ===
```
Comment (Moelf) [inline test/internals.jl:186]: `true ===` is extra now I think

**Comment by KristofferC** [comment]
I just want to say that the idea of loading packages based on some dynamic information in `__init__` is not a good idea. It kind of breaks the precompilation system. I'd suggest just taking the hit of either having to download the artifacts for both micromamba and pixi or make the artifacts lazy so they are only used when first accessed.
